server:
  port: 10180
#  tomcat:
#    native: true
spring:
  application:
    name: concertbook
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9099/~/concert_book
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
springfox:
  documentation:
    enabled: true
logging:
  level:
    root: INFO

#mybatis:
#  mapper-locations:
#    - mappers/*.xml